In [3]:
text = "& Juliet Running time: 2 hours and 30 minutes, including intermission Opened November 17, 2022 Click here to read the reviews. To purchase tickets, click here. Stephen Sondheim Theatre: 124 W 43rd St, New York, NY 100136    Aladdin  Running time: 2 hours and 30 minutes, including intermission Opened March 20, 2014 Click here to read the reviews. To purchase tickets, click here.  New Amsterdam Theatre: 214 W 42nd St, New York, NY 10036 A Beautiful Noise Running time: 2 hours and 15 minutes, including intermission Opened December 4, 2022 Click here to read the reviews. To purchase tickets, click here.  Broadhurst Theatre: 235 W 44th St, New York, NY 10036 The Book of Mormon Running time: 2 hours and 30 minutes, including intermission Opened March 24, 2011 To purchase tickets, click here.  Eugene O'Neill Theatre: 230 W 49th St, New York, NY 10019   Camelot Running time: 3 hours, including intermission Opened April 13, 2023 Click here to read the reviews. To purchase tickets, click here. Vivian Beaumont Theatre: 150 W 65th St, New York, NY 10023 Chicago Running time: 2 hours and 30 minutes minutes, including intermission Opened November 14, 1996 To purchase tickets, click here.  Ambassador Theatre: 219 W 49th St, New York, NY 10019  Fat Ham Running time: 1 hour and 35 minutes, no intermission Opened April 12, 2023 Click here to read the reviews. To purchase tickets, click here. American Airlines Theatre: 227 W 42nd St, New York, NY 10036 Funny Girl Running time: 2 hours and 50 minutes, including intermission Opened April 24, 2022 Click here to read the reviews. To purchase tickets, click here. August Wilson Theatre: 245 W 52nd St, New York, NY 10019  Good Night, Oscar Running time: 1 hour and 40 minutes, no intermission Opened April 24, 2023 Click here to read the reviews. To purchase tickets, click here.  Belasco Theatre: 111 W 44th St, New York, NY 10036 Grey House Running time: 1 hour and 40 minutes, no intermission Opened May 30, 2023 Click here to read the reviews. To purchase tickets, click here. Lyceum Theatre: 149 W 45th St, New York, NY 1003 Hadestown Running time: 2 hours and 25 minutes, including intermission Opened April 17, 2019 Click here to read reviews. To buy tickets, click here. Walter Kerr Theatre: 219 W 48th St, New York, NY 10036  Hamilton Running time: 2 hours and 55 minutes, including intermission Opened August 6, 2015 Click here to read the reviews. To purchase tickets, click here.  Richard Rodgers Theatre: 226 W 46th St, New York, NY 10036 Harry Potter and the Cursed Child  Running time: 3 hours and 30 minutes, including intermission Opened December 7, 2021 Click here to read reviews for the updated production. To purchase tickets, click here. Lyric Theatre: 213 W 42nd St, New York, NY 10036 Here Lies Love Running time: 1 hour and 30 minutes, no intermission Opening July 20, 2023 To purchase tickets, click here. Broadway Theatre: 1681 Broadway (at W. 53rd St.), New York, NY 10019   Kimberly Akimbo Running time: 2 hours and 20 minutes, including intermission Opened November 10, 2022 Click here to read the reviews.  To purchase tickets, click here. Booth Theatre: 222 W 45th St, New York, NY 10036 Leopoldstadt Running time: 2 hours and 10 minutes, no intermission Opened October 2, 2022 Click here to read the reviews. To purchase tickets, click here. Longacre Theatre: 220 W 48th St, New York, NY 10036 Life of Pi Running time: 2 hours and 10 minutes, including intermission Opened March 30, 2022 Click here to read the reviews. To purchase tickets, click here. Schoenfeld Theatre: 236 W 45th St, New York, NY 10036 The Lion King Running time: 2 hours and 30 minutes, including intermission Opened November 13, 1997 To purchase tickets, click here. Minskoff Theatre: 200 W 45th St, New York, NY 10036  MJ Running time: 2 hours and 30 minutes, including intermission Opened February 1 Click here to read reviews. To purchase tickets, click here.  Neil Simon Theatre: 250 W 52nd St, New York, NY 10019  Moulin Rouge! Running time: 2 hours and 45 minutes, including intermission Opened July 25, 2019 Click here to read reviews.  To purchase tickets, click here. Al Hirschfeld Theatre: 302 W 45th St, New York, NY 10036   New York, New York Running time: 2 hours and 35 minutes, including intermission Opened April 26, 2023 Click here to read the reviews. To purchase tickets, click here. St. James Theatre: 246 W 44th St, New York, NY 10036  Once Upon a One More Time Running time: 2 hours and 30 minutes, including intermission Opening June 22, 2023 To purchase tickets, click here.  Marquis Theatre: 1535 Broadway (between 45th and 46th Streets), New York, NY 10036 Parade Running time: 2 hours and 30 minutes, including intermission Opened March 16, 2023 Click here to read the reviews. To purchase tickets, click here. Bernard B. Jacobs Theatre: 242 W 45th St, New York, NY 10036 Peter Pan Goes Wrong Running time: 2 hours and 5 minutes, including intermission Opened April 19, 2023 Click here to read reviews. To purchase tickets, click here. Ethel Barrymore Theatre: 243 W 47th St, New York, NY 10036  Prima Facie Running time: 1 hour and 40 minutes, no intermission Opened April 23, 2023 Click here to read the reviews. To purchase tickets, click here.  John Golden Theatre: 252 W 45th St, New York, NY 10036 Shucked Running time: 2 hours and 15 minutes, including intermission Opened April 4, 2023 Click here to read reviews. To purchase tickets, click here. Nederlander Theatre: 208 W 41st St, New York, NY 10036 The Sign in Sidney Brustein's Window Running time: 2 hours and 45 minutes, including intermission Opened April 27, 2023 Click here to read the reviews.  To purchase tickets, click here.  James Earl Jones Theatre: 138 W 48th St, New York, NY 10036 Six Running time: 1 hour and 20 minutes minutes, no intermission Opened October 3, 2021 Click here to read reviews.  To purchase tickets, click here.  Lena Horne Theatre: 256 W 47th St, New York, NY 10036   Some Like It Hot Running time: 2 hours and 30 minutes, including intermission Opened December 11, 2023 Click here to reviews. To purchase tickets, click here. Shubert Theatre: 225 W 44th St, New York, NY 10036 Sweeney Todd Running time: 2 hours and 30 minutes, including intermission Opened March 26, 2023 Click here to reviews. To purchase tickets, click here. Lunt-Fontanne Theatre: 205 W 46th St, New York, NY 10036  Wicked Running time: 2 hours and 30 minutes, including intermission Opened October 30, 2003 To purchase tickets, click here.  Gershwin Theatre: 222 W 51st St, New York, NY 10019"




In [4]:
import re
import pandas as pd

In [10]:
# Regular expression patterns for extracting information
pattern = r"(?P<show_name>.*?)\s+Running time:\s+(?P<running_time>.*?)\s+Opened\s+(?P<opened>.*?)\s+Click here.*?To purchase tickets, click here.\s+(?P<theatre_name>.*?)\s*:\s*(?P<theatre_address>.+?)$"
matches = re.findall(pattern, text, re.MULTILINE | re.DOTALL)

# Creating a DataFrame to store the extracted information
data = pd.DataFrame(matches, columns=['Show Name', 'Running Time', 'Opened', 'Theatre Name', 'Theatre Address'])

# Displaying the table
print(data)

  Show Name                                    Running Time  \
0  & Juliet  2 hours and 30 minutes, including intermission   

              Opened              Theatre Name  \
0  November 17, 2022  Stephen Sondheim Theatre   

                                     Theatre Address  
0  124 W 43rd St, New York, NY 100136    Aladdin ...  


In [13]:
data

Show Name                                    Running Time  \
0  & Juliet  2 hours and 30 minutes, including intermission   

              Opened              Theatre Name  \
0  November 17, 2022  Stephen Sondheim Theatre   

                                     Theatre Address  
0  124 W 43rd St, New York, NY 100136    Aladdin ...

In [7]:
data

Show Name                                    Running Time  \
0  & Juliet  2 hours and 30 minutes, including intermission   

              Opened              Theatre Name  \
0  November 17, 2022  Stephen Sondheim Theatre   

                                     Theatre Address  
0  124 W 43rd St, New York, NY 100136    Aladdin ...

In [8]:
# Regular expression patterns for extracting information
pattern = r"(?P<show_name>.*?)\s+Running time:\s+(?P<running_time>.*?)\s+Opened\s+(?P<opened>.*?)\n.*?(?P<theatre_name>.*?)\s*:\s*(?P<theatre_address>.+?)$"
matches = re.finditer(pattern, text, re.MULTILINE | re.DOTALL)

# Creating a DataFrame to store the extracted information
data = pd.DataFrame(matches, columns=['Show Name', 'Running Time', 'Opened', 'Theatre Name', 'Theatre Address'])

# Displaying the table
print(data)


Empty DataFrame
Columns: [Show Name, Running Time, Opened, Theatre Name, Theatre Address]
Index: []


In [15]:
text2

"                   Show Name              Running Time              Opened               Theatre Name                             Theatre Address\n0                   & Juliet   2 hours and 30 minutes  November 17, 2022   Stephen Sondheim Theatre            124 W 43rd St, New York, NY 100136\n1                   Aladdin   2 hours and 30 minutes     March 20, 2014     New Amsterdam Theatre           214 W 42nd St, New York, NY 10036\n2          A Beautiful Noise   2 hours and 15 minutes    December 4, 2022       Broadhurst Theatre           235 W 44th St, New York, NY 10036\n3        The Book of Mormon   2 hours and 30 minutes     March 24, 2011         Eugene O'Neill Theatre           230 W 49th St, New York, NY 10019\n4                   Camelot          3 hours, including intermission        April 13, 2023          Vivian Beaumont Theatre          150 W 65th St, New York, NY 10023\n5                   Chicago   2 hours and 30 minutes    November 14, 1996         Ambassador Theatre  

In [14]:
text2="""                   Show Name              Running Time              Opened               Theatre Name                             Theatre Address
0                   & Juliet   2 hours and 30 minutes  November 17, 2022   Stephen Sondheim Theatre            124 W 43rd St, New York, NY 100136
1                   Aladdin   2 hours and 30 minutes     March 20, 2014     New Amsterdam Theatre           214 W 42nd St, New York, NY 10036
2          A Beautiful Noise   2 hours and 15 minutes    December 4, 2022       Broadhurst Theatre           235 W 44th St, New York, NY 10036
3        The Book of Mormon   2 hours and 30 minutes     March 24, 2011         Eugene O'Neill Theatre           230 W 49th St, New York, NY 10019
4                   Camelot          3 hours, including intermission        April 13, 2023          Vivian Beaumont Theatre          150 W 65th St, New York, NY 10023
5                   Chicago   2 hours and 30 minutes    November 14, 1996         Ambassador Theatre           219 W 49th St, New York, NY 10019
6                   Fat Ham   1 hour and 35 minutes, no intermission     April 12, 2023     American Airlines Theatre          227 W 42nd St, New York, NY 10036
7                Funny Girl   2 hours and 50 minutes, including intermission    April 24, 2022       August Wilson Theatre          245 W 52nd St, New York, NY 10019
8            Good Night, Oscar  1 hour and 40 minutes, no intermission  April 24, 2023            Belasco Theatre          111 W 44th St, New York, NY 10036
9                 Grey House   1 hour and 40 minutes, no intermission       May 30, 2023                Lyceum Theatre          149 W 45th St, New York, NY 1003
10                 Hadestown   2 hours and 25 minutes, including intermission   April 17, 2019          Walter Kerr Theatre          219 W 48th St, New York, NY 10036
11                 Hamilton   2 hours and 55 minutes, including intermission     August 6, 2015          Richard Rodgers Theatre          226 W 46th St, New York, NY 10036
12  Harry Potter and the Cursed Child   3 hours and 30 minutes, including intermission  December 7, 2021                 Lyric Theatre          213 W 42nd St, New York, NY 10036
13          Here Lies Love   1 hour and 30 minutes, no intermission   July 20, 2023         Broadway Theatre   1681 Broadway (at W. 53rd St.), New York, NY 10019
14         Kimberly Akimbo   2 hours and 20 minutes, including intermission  November 10, 2022                Booth Theatre          222 W 45th St, New York, NY 10036
15             Leopoldstadt   2 hours and 10 minutes, no intermission    October 2, 2022             Longacre Theatre          220 W 48th St, New York, NY 10036
16                Life of Pi   2 hours and 10 minutes, including intermission     March 30, 2022         Schoenfeld Theatre          236 W 45th St, New York, NY 10036
17           The Lion King   2 hours and 30 minutes, including intermission   November 13, 1997              Minskoff Theatre          200 W 45th St, New York, NY 10036
18                  MJ   2 hours and 30 minutes, including intermission  February 1                  Neil Simon Theatre          250 W 52nd St, New York, NY 10019
19            Moulin Rouge!   2 hours and 45 minutes, including intermission     July 25, 2019           Al Hirschfeld Theatre          302 W 45th St, New York, NY 10036
20         New York, New York   2 hours and 35 minutes, including intermission   April 26, 2023                St. James Theatre          246 W 44th St, New York, NY 10036
21   Once Upon a One More Time   2 hours and 30 minutes, including intermission    June 22, 2023                Marquis Theatre          1535 Broadway (between 45th and 46th Streets), New York, NY 10036
22                 Parade   2 hours and 30 minutes, including intermission     March 16, 2023             Bernard B. Jacobs Theatre          242 W 45th St, New York, NY 10036
23       Peter Pan Goes Wrong   2 hours and 5 minutes, including intermission     April 19, 2023           Ethel Barrymore Theatre          243 W 47th St, New York, NY 10036
24             Prima Facie   1 hour and 40 minutes, no intermission       April 23, 2023                John Golden Theatre          252 W 45th St, New York, NY 10036
25                  Shucked   2 hours and 15 minutes, including intermission     April 4, 2023             Nederlander Theatre          208 W 41st St, New York, NY 10036
26  The Sign in Sidney Brustein's Window   2 hours and 45 minutes, including intermission  April 27, 2023                James Earl Jones Theatre          138 W 48th St, New York, NY 10036
27                      Six   1 hour and 20 minutes minutes, no intermission  October 3, 2021               Lena Horne Theatre          256 W 47th St, New York, NY 10036
28          Some Like It Hot   2 hours and 30 minutes, including intermission  December 11, 2023                Shubert Theatre          225 W 44th St, New York, NY 10036
29              Sweeney Todd   2 hours and 30 minutes, including intermission     March 26, 2023          Lunt-Fontanne Theatre          205 W 46th St, New York, NY 10036
30                  Wicked   2 hours and 30 minutes, including intermission   October 30, 2003              Gershwin Theatre          222 W 51st St, New York, NY 10019
"""

In [23]:
# Split the text into rows
rows = text2.split('\n')

# Extract column names
columns = [column.strip() for column in rows[0].split('  ') if column.strip()]

# Create an empty list to store the table data
data = []

# Iterate over the remaining rows and extract the values
for row in rows[1:]:
    values = [value.strip() for value in row.split('  ') if value.strip()][1:]
    data.append(values)

# Create a DataFrame from the data
df = pd.DataFrame(data, columns=columns)

# Display the DataFrame
df.to_csv('theatre_data.csv', index=False)

                   Show Name              Running Time              Opened               Theatre Name                             Theatre Address
0                   & Juliet   2 hours and 30 minutes  November 17, 2022   Stephen Sondheim Theatre            124 W 43rd St, New York, NY 100136
1                   Aladdin   2 hours and 30 minutes     March 20, 2014     New Amsterdam Theatre           214 W 42nd St, New York, NY 10036
2          A Beautiful Noise   2 hours and 15 minutes    December 4, 2022       Broadhurst Theatre           235 W 44th St, New York, NY 10036
3        The Book of Mormon   2 hours and 30 minutes     March 24, 2011         Eugene O'Neill Theatre           230 W 49th St, New York, NY 10019
4                   Camelot          3 hours, including intermission        April 13, 2023          Vivian Beaumont Theatre          150 W 65th St, New York, NY 10023
5                   Chicago   2 hours and 30 minutes    November 14, 1996         Ambassador Theatre           219 W 49th St, New York, NY 10019
6                   Fat Ham   1 hour and 35 minutes, no intermission     April 12, 2023     American Airlines Theatre          227 W 42nd St, New York, NY 10036
7                Funny Girl   2 hours and 50 minutes, including intermission    April 24, 2022       August Wilson Theatre          245 W 52nd St, New York, NY 10019
8            Good Night, Oscar  1 hour and 40 minutes, no intermission  April 24, 2023            Belasco Theatre          111 W 44th St, New York, NY 10036
9                 Grey House   1 hour and 40 minutes, no intermission       May 30, 2023                Lyceum Theatre          149 W 45th St, New York, NY 1003
10                 Hadestown   2 hours and 25 minutes, including intermission   April 17, 2019          Walter Kerr Theatre          219 W 48th St, New York, NY 10036
11                 Hamilton   2 hours and 55 minutes, including intermission     August 6, 2015          Richard Rodgers Theatre          226 W 46th St, New York, NY 10036
12  Harry Potter and the Cursed Child   3 hours and 30 minutes, including intermission  December 7, 2021                 Lyric Theatre          213 W 42nd St, New York, NY 10036
13          Here Lies Love   1 hour and 30 minutes, no intermission   July 20, 2023         Broadway Theatre   1681 Broadway (at W. 53rd St.), New York, NY 10019
14         Kimberly Akimbo   2 hours and 20 minutes, including intermission  November 10, 2022                Booth Theatre          222 W 45th St, New York, NY 10036
15             Leopoldstadt   2 hours and 10 minutes, no intermission    October 2, 2022             Longacre Theatre          220 W 48th St, New York, NY 10036
16                Life of Pi   2 hours and 10 minutes, including intermission     March 30, 2022         Schoenfeld Theatre          236 W 45th St, New York, NY 10036
17           The Lion King   2 hours and 30 minutes, including intermission   November 13, 1997              Minskoff Theatre          200 W 45th St, New York, NY 10036
18                  MJ   2 hours and 30 minutes, including intermission  February 1                  Neil Simon Theatre          250 W 52nd St, New York, NY 10019
19            Moulin Rouge!   2 hours and 45 minutes, including intermission     July 25, 2019           Al Hirschfeld Theatre          302 W 45th St, New York, NY 10036
20         New York, New York   2 hours and 35 minutes, including intermission   April 26, 2023                St. James Theatre          246 W 44th St, New York, NY 10036
21   Once Upon a One More Time   2 hours and 30 minutes, including intermission    June 22, 2023                Marquis Theatre          1535 Broadway (between 45th and 46th Streets), New York, NY 10036
22                 Parade   2 hours and 30 minutes, including intermission     March 16, 2023             Bernard B. Jacobs Theatre          242 W 45th St, New York, NY 10036
23       Peter Pan Goes Wrong   2 hours and 5 minutes, including intermission     April 19, 2023           Ethel Barrymore Theatre          243 W 47th St, New York, NY 10036
24             Prima Facie   1 hour and 40 minutes, no intermission       April 23, 2023                John Golden Theatre          252 W 45th St, New York, NY 10036
25                  Shucked   2 hours and 15 minutes, including intermission     April 4, 2023             Nederlander Theatre          208 W 41st St, New York, NY 10036
26  The Sign in Sidney Brustein's Window   2 hours and 45 minutes, including intermission  April 27, 2023                James Earl Jones Theatre          138 W 48th St, New York, NY 10036
27                      Six   1 hour and 20 minutes minutes, no intermission  October 3, 2021               Lena Horne Theatre          256 W 47th St, New York, NY 10036
28          Some Like It Hot   2 hours and 30 minutes, including intermission  December 11, 2023                Shubert Theatre          225 W 44th St, New York, NY 10036
29              Sweeney Todd   2 hours and 30 minutes, including intermission     March 26, 2023          Lunt-Fontanne Theatre          205 W 46th St, New York, NY 10036
30                  Wicked   2 hours and 30 minutes, including intermission   October 30, 2003              Gershwin Theatre          222 W 51st St, New York, NY 10019
